// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNVN5lzvGfopI2H_FWU6HGB0ZcZ8mga-o',
    appId: '1:57302069433:web:e6de1bfb70baba6e952b68',
    messagingSenderId: '57302069433',
    projectId: 'chat-app-506d1',
    authDomain: 'chat-app-506d1.firebaseapp.com',
    storageBucket: 'chat-app-506d1.firebasestorage.app',
    measurementId: 'G-46VKFSRM5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTQE-TVcA9vn3CrRbv0be2ZbEXD_-EQ8',
    appId: '1:57302069433:android:f75c45cf9a996c9c952b68',
    messagingSenderId: '57302069433',
    projectId: 'chat-app-506d1',
    storageBucket: 'chat-app-506d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt6b-ARzcR9P2qSy4qZjGA8RXI7Kej3_c',
    appId: '1:57302069433:ios:291f832d983fd158952b68',
    messagingSenderId: '57302069433',
    projectId: 'chat-app-506d1',
    storageBucket: 'chat-app-506d1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
